spring:
  application:
    name: mockdemo

mock:
  mode: "NO"

external:
  service:
    url: https://api.restful-api.dev

logging:
  level:
    'com.github.tomakehurst.wiremock': DEBUG
    'org.eclipse.jetty': DEBUG
    'javax.management': INFO
    'sun.rmi': INFO
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} [%class] - %msg%n"